### ISSUE TITLE
Problems with Include.fsx using Jupyter 4.1

### ISSUE THREAD

**Issue by ndalchau** [fsprojects/IfSharp#53]
I recently reimaged my machine, with only VS2015 installed (no VS2013). I found a workaround to get Ifsharp working, by changing App.config to use the latest MSBuild.

There is a problem with the automatic running of Include.fsx, which produces error messages in my log file:
```
2016-03-01 16:36:04 - input.fsx(8,1): error FS0082: Could not resolve this reference. Could not locate the assembly "FSharp.Data.TypeProviders.dll". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. (Code=MSB3245)
2016-03-01 16:36:04 - input.fsx(8,1): error FS0084: Assembly reference 'FSharp.Data.TypeProviders.dll' was not found or is invalid
```
I was able to workaround this by commenting out the TypeProvider.dll reference in Include.fsx.

This raises the question about whether to automatically include DLLs using this strategy. There have been similar issues with including FSharp.Charting: #52

**Comment by npmurphy** [comment]
Commenting out the reference to the bundled TypeProvider.dll reference in Include.fsx makes ifsharp work with mono 4.2.2, F# 4.0.

Using Paket to get appropriate dlls for the system at installation time seems like reasonable way forward.

**Comment by cgravill** [comment]
I'm happy to remove these references if it's convenient to get them by Nuget (or Paket). 
@npmurphy do you have a working solution you can share with "#load fscharting.fsx" for the helper functions in IfSharp?

**Comment by cgravill** [comment]
For reference, the change required to app.config is:

```XML
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Framework" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-14.0.0.0" newVersion="14.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Engine" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-14.0.0.0" newVersion="14.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-14.0.0.0" newVersion="14.0.0.0"/>
      </dependentAssembly>
```

I'm not sure the best way to do this AND support Visual Studio 2013.

**Comment by cgravill** [comment]
I've done ahead and commented `#r "FSharp.Data.TypeProviders.dll"` in Include.fsx to get away from this problem. It can be added via `NuGet #N "FSharp.Data.TypeProviders"` within a given notebook which is still fairly convenient.

**Comment by cgravill** [comment]
As part of #61 I've upgraded the F# Compiler Service which seems to address MSBuild mismatch above.

**Comment by cgravill** [comment]
The issues here have now been resolved by a combination of #61 #64. IfSharp should now start cleanly even with only recent Visual Studio installs (and on other platforms too).

It seems like moving more dlls out as @npmurphy suggests will make it more flexible for users as well.
